"""Smoke test for scripts/10_final_assessment.py.

This script depends on data/processed/mimic_similarities.parquet, which is
generated by scripts/08_compare_mimics.py. We don't want to re-embed all 648
mimic drafts here, so we skip if the parquet isn't present. When it is, we
just check that the script writes its 4 result CSVs and the figure, and that
the Friedman test rejects the null at q=0.05.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]


def test_final_assessment_runs_and_produces_outputs() -> None:
    parquet = REPO_ROOT / "data" / "processed" / "mimic_similarities.parquet"
    if not parquet.exists():
        pytest.skip("mimic_similarities.parquet not present; "
                    "run scripts/08_compare_mimics.py first")
    subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "10_final_assessment.py")],
        cwd=REPO_ROOT, check=True, capture_output=True,
    )
    expected = [
        REPO_ROOT / "results" / "final_pairwise_tests.csv",
        REPO_ROOT / "results" / "final_win_vs_human.csv",
        REPO_ROOT / "results" / "final_friedman.csv",
        REPO_ROOT / "results" / "final_per_scenario.csv",
        REPO_ROOT / "figures" / "fig10_final_assessment.png",
        REPO_ROOT / "figures" / "fig10_final_assessment.pdf",
    ]
    for p in expected:
        assert p.exists(), f"expected output missing: {p}"

    import pandas as pd
    fr = pd.read_csv(REPO_ROOT / "results" / "final_friedman.csv").iloc[0]
    assert fr["chi2"] > 50.0, f"Friedman chi2 unexpectedly small: {fr['chi2']}"
    assert fr["p"] < 0.05, f"Friedman p unexpectedly large: {fr['p']}"

    pairs = pd.read_csv(REPO_ROOT / "results" / "final_pairwise_tests.csv")
    assert len(pairs) == 6, f"expected 6 pairwise tests, got {len(pairs)}"
    # Five pairs should be BH-significant; the LLM-vs-LLM pair is the expected exception.
    sig = pairs[pairs["bh_reject"]]
    assert len(sig) >= 5, f"expected >=5 BH-FDR-significant pairs, got {len(sig)}"

    wins = pd.read_csv(REPO_ROOT / "results" / "final_win_vs_human.csv")
    assert len(wins) == 3, f"expected 3 win-rate rows, got {len(wins)}"
    assert (wins["n"] == 324).all(), "win-rate denominators should all be 324"
