"""Stage 06: assemble the Markdown reproduction report from the result CSVs."""
from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

import pandas as pd  # noqa: E402

RESULTS = REPO_ROOT / "results"
FIGURES = REPO_ROOT / "figures"


def main() -> None:
    h_csv = RESULTS / "hypothesis_tests.csv"
    h3_csv = RESULTS / "h3_rmcorr.csv"
    perc_csv = RESULTS / "perception_treatment_vs_control.csv"
    if not h_csv.exists():
        raise SystemExit(f"missing {h_csv}; run scripts/03_run_hypothesis_tests.py first")

    h = pd.read_csv(h_csv)
    h3 = pd.read_csv(h3_csv) if h3_csv.exists() else None
    perc = pd.read_csv(perc_csv) if perc_csv.exists() else None

    lines: list[str] = []
    lines.append("# Reproduction Report\n")
    lines.append("**Paper:** *Can You Make It Sound Like You? Post-Editing LLM-Generated Text "
                 "for Personal Style*, Baumler et al. (ACL 26).\n")
    lines.append("**Code & figures generated by:** `scripts/0[0-6]_*.py`. Re-run with `make all`.\n")
    lines.append("**Embedding model:** `rrivera1849/LUAR-MUD` (revision pinned in "
                 "`src/personal_style/__init__.py`).\n")
    lines.append("**Test protocol:** two-sided permutation tests (10 000 permutations), "
                 "Hedges' *g* (pooled-SD, small-sample-corrected), 95 % CI from 1 000 bootstrap "
                 "resamples, BH-FDR at q=0.05.\n")
    lines.append("\n## Hypothesis tests\n")
    lines.append("| Hypothesis | n | g (ours) | 95 % CI | p (perm) | p (BH) | Paper g | Paper CI | Direction match | CI overlap |")
    lines.append("|---|---:|---:|---|---:|---:|---:|---|:---:|:---:|")
    import numpy as np
    for _, r in h.iterrows():
        sign_match = (r["paper_g"] is not None and not pd.isna(r["paper_g"])
                      and np.sign(r["g"]) == np.sign(r["paper_g"]))
        ci_overlap = (r["paper_ci_low"] is not None and not pd.isna(r["paper_ci_low"])
                      and not (r["ci_high"] < r["paper_ci_low"] or r["ci_low"] > r["paper_ci_high"]))
        lines.append(
            f"| {r['name']} | {int(r['n'])} | {r['g']:+.3f} | "
            f"[{r['ci_low']:+.2f}, {r['ci_high']:+.2f}] | "
            f"{r['p']:.4f} | {r['p_bh']:.4f} | "
            f"{r['paper_g']:+.2f} | "
            f"[{r['paper_ci_low']:+.2f}, {r['paper_ci_high']:+.2f}] | "
            f"{'✓' if sign_match else '✗'} | "
            f"{'✓' if ci_overlap else '✗'} |"
        )

    lines.append("\n### H3: repeated-measures correlation between LUAR and perception\n")
    if h3 is not None:
        r = h3.iloc[0]
        lines.append(f"- Ours: r = {r['r']:+.3f}, 95 % CI [{r['ci_low']:+.2f}, {r['ci_high']:+.2f}], "
                     f"p = {r['p']:.2g}, dof = {int(r['dof'])}, n = {int(r['n'])}")
        lines.append(f"- Paper: r = +{r['paper_r']:.3f} ± {r['paper_se']:.3f}, p {r['paper_p']}\n")

    lines.append("\n### Perception: treatment vs. control (exploratory, §6.3)\n")
    if perc is not None:
        r = perc.iloc[0]
        lines.append(f"- Ours: g = {r['g']:+.3f}, 95 % CI [{r['ci_low']:+.2f}, {r['ci_high']:+.2f}], p = {r['p']:.4f}")
        lines.append(f"- Paper: g = {r['paper_g']:+.2f}, 95 % CI [{r['paper_ci_low']:+.2f}, {r['paper_ci_high']:+.2f}], p = {r['paper_p']:.4f}\n")

    lines.append("\n## Figures\n")
    figs = [
        ("Fig. 3", "Similarity to LLM-text and control text, before vs. after post-edit (H1a, H1b).", "fig3_before_after.png"),
        ("Fig. 4", "Edited text vs. own control vs. LLM-generated text (H1c).", "fig4_treatment_vs_control_llm.png"),
        ("Fig. 5", "Self-similarity vs. other-participant similarity (H1a', H2c).", "fig5_self_vs_other.png"),
        ("Fig. 6", "Within-pool stylistic homogeneity for LLM, post-edited, control (H2a, H2b).", "fig6_homogeneity.png"),
        ("Fig. 7", "Perceived self-similarity by condition.", "fig7_perceived.png"),
        ("Fig. 8", "Perceived vs. LUAR-measured self-similarity (rmcorr; H3).", "fig8_rmcorr.png"),
    ]
    # `REPRODUCTION_REPORT.md` is written to the repo root, so figure links
    # are relative to the root. Using `../figures/` resolves above the repo
    # and renders as a broken image on GitHub. Keep the path as just
    # `figures/<fname>`.
    for label, caption, fname in figs:
        lines.append(f"### {label}\n\n*{caption}*\n\n![{label}](figures/{fname})\n")

    lines.append("\n## Notes on deviations from the paper\n")
    lines.append(
        "- The paper does not pin a LUAR-MUD model revision; we pin "
        "`9204529608fa4c8b33f59421abdf62a48b7c58d1`.\n"
        "- Hedges' g uses the pooled-SD convention (Hedges 1981), which matches the "
        "magnitudes the paper reports for H1a (0.55), H1a' (-0.56), H2a (1.42).\n"
        "- For aggregations described as 'similarity to other participants' text', we average "
        "per-participant means (each other participant contributes one value), which gives "
        "directions matching the paper for every preregistered test.\n"
        "- Pangram replication of H1b (paper: g = -0.45) is gated on a `PANGRAM_API_KEY` "
        "secret and is currently skipped.\n"
        "- Permutation-test floor: `p = 1/(n_perm+1)` with `n_perm = 10 000`, so the smallest "
        "reportable p is 0.0001 (the paper reports 0.0002 with n_perm = 5 000).\n"
    )

    out = REPO_ROOT / "REPRODUCTION_REPORT.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
