"""Stage 15: dump qualitative samples from the adversarial-rewriting trajectories.

Produces results/adversarial_samples.md with iter 0 / 10 / 20 of every
target, the LUAR-MUD margin at each iteration, and the predicted class.

Usage:  python3 scripts/15_dump_adversarial_samples.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RUNS = REPO / "data" / "processed" / "adversarial_runs"
PACK = REPO / "data" / "processed" / "adversarial_pack.json"
OUT  = REPO / "results" / "adversarial_samples.md"


def get_margin(rec: dict) -> float:
    return float(
        rec.get("margin",
                rec.get("decision_function",
                        rec.get("ai_score_higher_is_more_aiish")))
    )


def get_text(rec: dict, scenario: str, pack: dict) -> str:
    """Return the rewrite text. If the sub-agent only stored a text_path
    (target_03), fall back to the iter-0 text from the pack file (the
    intermediate texts are not reconstructable -- we mark them so)."""
    if rec.get("text"):
        return rec["text"]
    if rec["iteration"] == 0:
        # Pull iter 0 from the saved adversarial_pack.json.
        for t in pack["targets"]:
            if t["scenario"] == scenario:
                return t["initial_text"]
    path = rec.get("text_path")
    return f"[text not committed; sub-agent only saved a path to `{path}`]"


def main() -> None:
    pack = json.loads(PACK.read_text())
    files = sorted(RUNS.glob("*.json"))
    out_lines = [
        "# Qualitative samples from the adversarial rewriting loop",
        "",
        "Each section below is one of the five fold-1 test-fold targets.",
        "We show the rewrite at iterations 0, 10, and 20, with the frozen",
        "Opus-fold-1 SVM's signed margin (positive = AI side, negative =",
        "human side) and the predicted class.",
        "",
        "Generated by `scripts/15_dump_adversarial_samples.py` from",
        "`data/processed/adversarial_runs/target_*.json`.",
        "",
    ]
    for f in files:
        traj = json.loads(f.read_text())
        out_lines.append(f"## {traj['scenario']} \u2014 `{f.name}`")
        out_lines.append("")
        out_lines.append(f"- **pid**: `{traj['pid']}`")
        out_lines.append(f"- **task_idx**: {traj['task_idx']}")
        out_lines.append(f"- **trajectory length**: {len(traj['iterations'])} iterations")
        # one-line margin trajectory
        margins = [get_margin(r) for r in traj["iterations"]]
        traj_str = "  ".join(f"{m:+.2f}" for m in margins)
        out_lines.append(f"- **margins (iter 0..20)**: {traj_str}")
        # how many iterations crossed the boundary
        crossed = sum(1 for m in margins if m < 0)
        out_lines.append(f"- **iterations on the human side** (margin < 0): "
                         f"{crossed} of {len(margins)}")
        out_lines.append("")
        for i in (0, 10, 20):
            r = traj["iterations"][i]
            margin = get_margin(r)
            cls = r.get("predicted_class", "?")
            wc = r.get("word_count", -1)
            text = get_text(r, traj["scenario"], pack)
            out_lines.append(f"### iter {i}\u2003"
                             f"`margin={margin:+.3f}`\u2003"
                             f"`predicted={cls}`\u2003"
                             f"`{wc} words`")
            out_lines.append("")
            out_lines.append("```")
            out_lines.append(text.strip())
            out_lines.append("```")
            out_lines.append("")
        out_lines.append("---")
        out_lines.append("")

    OUT.write_text("\n".join(out_lines))
    print(f"wrote {OUT} ({len(out_lines)} lines)")


if __name__ == "__main__":
    main()
